#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int glsurfaceview_camera = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int publish = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int record = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int swCam = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int swEnc = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int amaro = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int antique = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int beauty = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int blackcat = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int brannan = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int brightness = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int brooklyn = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int calm = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int constrast = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int cool = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int crayon = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int earlybird = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int emerald = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int evergreen = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int exposure = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int fragment = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int freud = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int healthy = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int hefe = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int hudson = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hue = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int inkwell = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int kevin_new = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int latte = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int lomo = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int lookup = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int n1977 = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int nashville = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int nostalgia = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int pixar = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int rise = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int romance = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int sakura = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int saturation = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int sharpen = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int sierra = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int sketch = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int skinwhiten = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int suger_tablets = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int sunrise = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int sunset = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int sutro = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int sweets = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int tender = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int toaster2_filter_shader = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int valencia = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int vertex = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int vertex_sharpen = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int walden = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int warm = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int whitecat = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int xproii_filter_shader = 2130968627;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
